version: "3.5"

# This expects to be run as an override of trillian's example docker deployment.
# See the README in the main directory for instructions.
# This won't scale to multiple replicas without much more work.

services:
  personality:
    build:
#      context: ./trillian-examples
#      dockerfile: ./binary_transparency/firmware/cmd/ft_personality/Dockerfile
    build:
       context: ./binary_transparency/personality
       dockerfile: Dockerfile.personality
    command: [
      "--alsologtostderr",
      "--v=2",
      "--listen=:8000",
      "--trillian=trillian-log-server:8090",
      "--connect_timeout=30s",
      "--cas_db_file=/opt/ft.db"
    ]
    ports:
     - "8000:8000"
    restart: always
    environment:
      - SCONE_HEAP=2G
      - SCONE_LOG=7
      - SCONE_MODE=AUTO
      - SCONE_VERSION=1
    devices:
       - /dev/isgx


networks:
  default:
      external:
         name: trillian-net
